# Generated by Django 3.1.4 on 2021-01-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20210105_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated']},
        ),
    ]
